services:
  munters.server:
    build:
      context: .
      dockerfile: Munters.Server/Dockerfile
    image: muntersserver:dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Giphy__ApiKey=${GIPHY__APIKEY}
      - Cors__AllowedOrigins=${Cors__AllowedOrigins}
    restart: unless-stopped
    networks:
      - muntersnet

  munters.client:
    build:
      context: ./munters.client
      dockerfile: Dockerfile
    image: muntersclient:dev
    ports:
      - "3000:80"
    depends_on:
      - munters.server
    restart: unless-stopped
    networks:
      - muntersnet
